### ISSUE TITLE
Duplicate? 

### ISSUE THREAD

**Issue by megaw4tt** [cosmonot1/MineralCatalog#15]
Is it possible to have a duplicate and edit mode??

**Comment by cosmonot1** [comment]
Edit mode already exists. From the specimen list view hit the edit button below the specimen photo. It will open the edit view with all of the data already populated. Simply edit any field and hit the update button and it will update the entry in the DB. I'll start working on a duplicate feature.

**Comment by cosmonot1** [comment]
Edit mode already exists. From the specimen list view hit the edit button below the specimen photo. It will open the edit view with all of the data already populated. Simply edit any field and hit the update button and it will update the entry in the DB. I'll start working on a duplicate feature.

**Comment by cosmonot1** [comment]
Duplicate mode added. Click the duplicate button on any specimen to make another version. It will open the edit/add view with all of the fields populated except for the photos and analysis document fields. After adding, only photos and documents will clear so you can duplicate a bunch of one specimen easily.
