### ISSUE TITLE
Additional fields 

### ISSUE THREAD

**Issue by megaw4tt** [cosmonot1/MineralCatalog#16]
MODIFIERS. (Check boxes)
On ___
In___
With___
After___

GEOLOGY (check boxes)

Metamorphic ___
Pegmatite ___
Porphyry ___
CRD/Skarn ___
Epithermal Vein ___
Volcanic Related ___
Exhalite ___
MVT ___
Evaporite ___
Other __________________________________

EXHIBIT HISTORY  (These need to be linear  Tucson  1998  Comp Award  with room for many lines 15-20 min
Show____________________ Year ____
Comp ____
Award _______________________

FEATURES (check boxes)
Twinned___
Pseudomorph___
Inclusions___
Photosensitive___

FLUORESCENCE (check box with comment box below for color) 
SW ________________
LW ________________

QUALITY (check box) 
Exceptional ___
Exhibit___
Locality___
Study___

ADD TO LOCALITY 
(Check box)
Type Locality___
 (Check box followed by date)
Self Collected ___ When ______ 

(Check box followed by space for a name and then attachement) 
Photographed___  by _________________ Photo File #________________

**Comment by cosmonot1** [comment]
Additional photo upload for professional photographer photos of minerals. Thats what the photographed, by, and file # are for.
