### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by megaw4tt** [cosmonot1/MineralCatalog#28]
I need a section (that won't be on the printout) about Labels/prior owners

Provenance (the name of the section)
Old labels (check box) 
Prior labels (check box)
Former Owners ____________________________ year acquired (by them) _____
 prior catalog number ____Label (check box)
Miguel Romero (check box) and catalog number _______

Have spot to upload a scans of labels

**Comment by cosmonot1** [comment]
@megaw4tt What is the difference between Old labels and Prior labels? Seems redundant.
